#!/bin/bash

OS=$(uname)

if [[ "$OS" == "Darwin" ]]; then
    echo "Running on macOS"
    ./scripts/pre-commit-linux.sh
elif [[ "$OS" == "Linux" ]]; then
    echo "Running on Linux"
    ./scripts/pre-commit-linux.sh
elif [[ "$OS" =~ MINGW|CYGWIN ]]; then
    echo "Running on Windows"
    exec powershell.exe -ExecutionPolicy RemoteSigned -File '.\pre-commit-win.ps1'
else
    echo "Unsupported OS: $OS"
    exit 1
fi
