# Generated by Django 4.2.18 on 2025-03-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
