# Generated by Django 4.2.18 on 2025-03-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_eventowner_image_usersettings_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventOwner',
            new_name='Event',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='event_id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='file_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
