# Generated by Django 4.2.18 on 2025-03-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_eventowner_event_rename_event_event_event_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='eventcontent',
            name='event_name',
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='firebase_id',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
