# Generated by Django 4.2.18 on 2025-03-08 01:59

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Event = apps.get_model("app", "Event")
    for row in Event.objects.all():
        row.obfuscated_event_id = uuid.uuid4()
        row.save(update_fields=["obfuscated_event_id"])

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event_last_modified'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
