# Generated by Django 4.2.18 on 2025-03-04 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_owner_id_event_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuser',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event'),
        ),
    ]
