# Generated by Django 4.2.18 on 2025-03-08 01:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20250308_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='obfuscated_event_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
