# Generated by Django 4.2.18 on 2025-03-15 02:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_event_obfuscated_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='obfuscated_event_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
