# Generated by Django 4.2.18 on 2025-03-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_event_obfuscated_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoredby',
            name='score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
