# Generated by Django 4.2.18 on 2025-03-17 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_scoredby_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="user",
            field=models.ForeignKey(
                default="c1cd8e6c-ee2b-440d-ac4b-3ff048c482fc",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.user",
            ),
            preserve_default=False,
        ),
    ]
