# Generated by Django 4.2.18 on 2025-03-24 17:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_image_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='event',
            name='obfuscated_event_id',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='accepted',
        ),
        migrations.AlterUniqueTogether(
            name='eventcontent',
            unique_together={('event', 'image')},
        ),
        migrations.CreateModel(
            name='EventInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, default='/', max_length=30, null=True, unique=True)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2025, 3, 25, 17, 15, 59, 651703, tzinfo=datetime.timezone.utc))),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('event', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app.event')),
            ],
        ),
        migrations.CreateModel(
            name='DirectInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to='app.user')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='app.user')),
            ],
            options={
                'unique_together': {('event', 'inviter', 'invitee')},
            },
        ),
    ]
