# Generated by Django 4.2.18 on 2025-03-25 00:39

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_user_image_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinvite',
            name='expiration_date',
            field=models.DateTimeField(default=app.models.default_expiration),
        ),
    ]
