# Generated by Django 4.2.18 on 2025-03-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_eventinvite_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinvite',
            name='link',
            field=models.CharField(blank=True, default='/', max_length=50, null=True, unique=True),
        ),
    ]
